In [3]:
import numpy as np

1. Creating NumPy Arrays

`Python list`

In [4]:
arr1 = np.array([1, 2, 3, 4, 5])
print("Array from list:", arr1)

Array from list: [1 2 3 4 5]


`Multi-dimensional array`

In [5]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

2D Array:
 [[1 2 3]
 [4 5 6]]


`Special arrays`

In [7]:
zeros = np.zeros((3, 3))   # 3x3 array of zeros
print("Array of zeros:\n", zeros)

Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
ones = np.ones((2, 4))     # 2x4 array of ones
print("Array of ones:\n", ones)

Array of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
identity = np.eye(3)       # 3x3 Identity matrix
print("Identity matrix:\n", identity)

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
range_arr = np.arange(0, 10, 2)  # Like Python range, but returns array
print("Array with range:", range_arr)

Array with range: [0 2 4 6 8]


In [11]:
linspace_arr = np.linspace(0, 1, 5)  # 5 points between 0 and 1
print("Array with linspace:", linspace_arr)

Array with linspace: [0.   0.25 0.5  0.75 1.  ]


2. Array Attributes

In [13]:
arr1.shape

(5,)

In [ ]:
arr2.shape

(2, 3)

In [16]:
arr2.dtype

dtype('int32')

3. Indexing and Slicing

In [17]:
arr3 = np.array([10, 20, 30, 40, 50])
print("Element at index 2:", arr3[2])
print("Slice 1:4:", arr3[1:4])

Element at index 2: 30
Slice 1:4: [20 30 40]


`2D indexing`

In [ ]:
print("Row 1, Col 2:", arr2[1, 2])
print("First row:", arr2[0, :]) 
print("First column:", arr2[:, 0]) 


Row 1, Col 2: 6
First row: [1 2 3]
First column: [1 4]


`Boolean indexing`

In [19]:
print("Elements > 25:", arr3[arr3 > 25])

Elements > 25: [30 40 50]


 4. Array Operations

In [20]:
arrA = np.array([1, 2, 3])
arrB = np.array([4, 5, 6])

`Element-wise operations`

In [21]:
print("Addition:", arrA + arrB)
print("Multiplication:", arrA * arrB)
print("Power:", arrA ** 2)

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Power: [1 4 9]


`Universal functions`

In [22]:
print("Sqrt:", np.sqrt(arrB))
print("Exp:", np.exp(arrA))
print("Sin:", np.sin(arrA))


Sqrt: [2.         2.23606798 2.44948974]
Exp: [ 2.71828183  7.3890561  20.08553692]
Sin: [0.84147098 0.90929743 0.14112001]


5. Matrix Operations

In [23]:
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])

`Matrix multiplication`

In [ ]:
print("Dot product:\n", np.dot(mat1, mat2))
print("@ operator:\n", mat1 @ mat2) 

Dot product:
 [[19 22]
 [43 50]]
@ operator:
 [[19 22]
 [43 50]]


`Transpose`

In [25]:
mat1.T

array([[1, 3],
       [2, 4]])

6. Statistics & Aggregations

In [26]:
stats_arr = np.array([1, 2, 3, 4, 5])
print("Sum:", np.sum(stats_arr))
print("Mean:", np.mean(stats_arr))
print("Median:", np.median(stats_arr))
print("Std Dev:", np.std(stats_arr))
print("Min:", np.min(stats_arr))
print("Max:", np.max(stats_arr))


Sum: 15
Mean: 3.0
Median: 3.0
Std Dev: 1.4142135623730951
Min: 1
Max: 5


7. Reshaping 

In [27]:
reshape_arr = np.arange(1, 10).reshape(3, 3)
print("Reshaped (3x3):\n", reshape_arr)

Reshaped (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


8. Random Numbers

In [28]:
rand_arr = np.random.rand(3, 3)    # Uniform [0,1)
print("Random array:\n", rand_arr)

Random array:
 [[0.64346647 0.70880686 0.03861705]
 [0.85201643 0.23204905 0.86980107]
 [0.85760831 0.63114782 0.45712827]]


In [30]:
rand_int = np.random.randint(0, 10, (3, 3))  # Random integers
print("Random integers:\n", rand_int)

Random integers:
 [[6 7 5]
 [8 9 6]
 [4 2 0]]


In [32]:
normal_arr = np.random.randn(3, 3) # Normal distribution
print("Normal distribution:\n", normal_arr)

Normal distribution:
 [[ 0.41650234 -1.51223942 -0.95149337]
 [ 1.2742611   0.35391908  0.2845023 ]
 [ 0.10252039 -0.9663255  -0.85508894]]


9. Copying and Views

In [37]:
orig = np.array([1, 2, 3])
view = orig.view()   # Shares data
copy = orig.copy()   # Independent copy

In [38]:
orig[0] = 99
print("Original:", orig)
print("View:", view)
print("Copy:", copy)

Original: [99  2  3]
View: [99  2  3]
Copy: [1 2 3]


10. NumPy for OpenCV

In [41]:
# Example grayscale (2D) and color (3D) shapes
height, width = 100, 200
img_gray = np.random.randint(0, 255, (height, width), dtype=np.uint8)
img_color = np.random.randint(0, 255, (height, width, 3), dtype=np.uint8)

In [ ]:
print("Grayscale shape:", img_gray.shape)
print("Color shape:", img_color.shape)

Grayscale shape: (100, 200)
Color shape: (100, 200, 3)


In [43]:
# Access a pixel (y, x) for grayscale
print("Gray pixel [10,20]:", img_gray[10, 20])

Gray pixel [10,20]: 239


In [44]:
# Access pixel (y, x, c) for color (channel: 0=Blue, 1=Green, 2=Red)
print("Color pixel [10,20] (BGR):", img_color[10, 20])


Color pixel [10,20] (BGR): [ 69 115 247]


In [45]:
# Convert data type (e.g., to float32)
float_img = img_gray.astype(np.float32)
print("Converted dtype:", float_img.dtype)

Converted dtype: float32
